import os
print("---------------")
print("download start....")
print("---------------")
os.system("python -m pip install --upgrade pip")
os.system("pip install bs4")
os.system("pip install requests")
os.system("pip install PyQt5")
os.system("pip install selenium")
os.system("pip install pyinstaller")
print("---------------")
print("all downloads are done")
print("---------------")